### ISSUE TITLE
Add xAPI statements (de)serialisers for Marsha and Ashley events

### ISSUE THREAD

**Issue by jmaupetit** [openfun/ralph#20]
### Purpose

Ralph should be able to read and write xAPI statements to move format from/to various standards.

### Proposal

Define Pydantic models for known/documented xAPI event types.

**Comment by quitterie-lcs** [comment]
# edX events

## Event sources

* server
* browser
* mobile
* task

## Common fields (root model)

* accept_language
* agent
* context.course_id
* context.org_id
* context.path
* context.user_id
* context.course_user_tags
* context.module
* event
* event_source
* event_type
* host
* ip
* name
* page 
* referer
* session 
* time
* username

## Student events

### Enrollment Events

* edx.course.enrollment.activated
* edx.course.enrollment.deactivated
* edx.course.enrollment.mode_changed
* edx.course.enrollment.upgrade.clicked
* edx.course.enrollment.upgrade.succeeded

### Navigational Events

* page_close
* seq_goto
* seq_next
* seq_prev

### Video Interaction Events

* hide_transcript/edx.video.transcript.hidden
* load_video/edx.video.loaded
* pause_video/edx.video.paused
* play_video/edx.video.played
* seek_video/edx.video.position.changed
* show_transcript/edx.video.transcript.shown
* speed_change_video
* stop_video/edx.video.stopped
* video_hide_cc_menu
* video_show_cc_menu

### Pre-Roll Video Interaction Events

* edx.video.bumper.dismissed
* edx.video.bumper.loaded
* edx.video.bumper.played
* edx.video.bumper.skipped
* edx.video.bumper.stopped
* edx.video.bumper.transcript.hidden
* edx.video.bumper.transcript.menu.hidden
* edx.video.bumper.transcript.menu.shown
* edx.video.bumper.transcript.shown

### Textbook Interaction Events

* book
* textbook.pdf.thumbnails.toggled
* textbook.pdf.thumbnail.navigated
* textbook.pdf.outline.toggled
* textbook.pdf.chapter.navigated
* textbook.pdf.page.navigated
* textbook.pdf.zoom.buttons.changed
* textbook.pdf.zoom.menu.changed
* textbook.pdf.display.scaled
* textbook.pdf.page.scrolled
* textbook.pdf.search.executed
* textbook.pdf.search.navigatednext
* textbook.pdf.search.highlight.toggled
* textbook.pdf.searchcasesensitivity.toggled

### Problem Interaction Events

* edx.problem.hint.demandhint_displayed
* edx.problem.hint.feedback_displayed
* problem_check
* problem_check_fail
* problem_graded
* problem_rescore
* problem_rescore_fail
* problem_reset
* problem_save
* problem_show
* reset_problem
* reset_problem_fail
* save_problem_fail
* save_problem_success
* showanswer

### Timed and Proctored Exam Events

* edx.special_exam.proctored.attempt.created
* edx.special_exam.practice.attempt.created
* edx.special_exam.timed.attempt.created
* edx.special_exam.proctored.attempt.declined
* edx.special_exam.proctored.attempt.deleted
* edx.special_exam.practice.attempt.deleted
* edx.special_exam.timed.attempt.deleted
* edx.special_exam.proctored.attempt.download_software_clicked 
* edx.special_exam.practice.attempt.download_software_clicked
* edx.special_exam.proctored.attempt.error
* edx.special_exam.practice.attempt.error
* edx.special_exam.proctored.attempt.ready_to_start
* edx.special_exam.practice.attempt.ready_to_start
* edx.special_exam.proctored.attempt.ready_to_submit
* edx.special_exam.practice.attempt.ready_to_submit
* edx.special_exam.timed.attempt.ready_to_submit
* edx.special_exam.proctored.attempt.rejected
* edx.special_exam.proctored.attempt.review_received
* edx.special_exam.proctored.attempt.started
* edx.special_exam.practice.attempt.started
* edx.special_exam.timed.attempt.started
* edx.special_exam.proctored.attempt.submitted
* edx.special_exam.practice.attempt.submitted
* edx.special_exam.timed.attempt.submitted
* edx.special_exam.proctored.attempt.verified
* edx.special_exam.proctored.option-presented

### Bookmark Events

* edx.bookmark.accessed
* edx.bookmark.added
* edx.bookmark.listed
* edx.bookmark.removed

### Notes Events

* edx.course.student_notes.added
* edx.course.student_notes.deleted
* edx.course.student_notes.edited
* edx.course.student_notes.notes_page_viewed
* edx.course.student_notes.searched
* edx.course.student_notes.used_unit_link
* edx.course.student_notes.viewed

### Library Interaction Events

* edx.librarycontentblock.content.assigned
* edx.librarycontentblock.content.removed

### Discussion Forum Events

* edx.forum.comment.created
* edx.forum.response.created
* edx.forum.response.voted
* edx.forum.searched
* edx.forum.thread.created
* edx.forum.thread.voted

### Open Response Assessment Events

* openassessmentblock.get_peer_submission
* openassessmentblock.get_submission_for_staff_grading
* openassessmentblock.peer_assess
* openassessmentblock.self_assess
* openassessmentblock.staff_assess
* openassessmentblock.submit_feedback_on_assessments
* openassessmentblock.create_submission
* openassessmentblock.save_submission
* openassessment.student_training_assess_example
* openassessment.upload_file

### Drag and Drop Events

* edx.drag_and_drop_v2.feedback.closed
* edx.drag_and_drop_v2.feedback.opened
* edx.drag_and_drop_v2.item.dropped
* edx.drag_and_drop_v2.item.picked_up
* edx.drag_and_drop_v2.loaded

### Peer Instruction Events

* ubc.peer_instruction.accessed
* ubc.peer_instruction.original_submitted
* ubc.peer_instruction.revised_submitted

### Poll and Survey Events

* xblock.poll.submitted
* xblock.poll.view_results
* xblock.survey.submitted
* xblock.survey.view_results

### Course Content Completion Event

* edx.done.toggled

### Third-Party Content Events

* edx.googlecomponent.calendar.displayed
* edx.googlecomponent.document.displayed
* oppia.exploration.completed
* oppia.exploration.loaded
* oppia.exploration.state.changed
* microsoft.office.mix.loaded
* microsoft.office.mix.paused
* microsoft.office.mix.played
* microsoft.office.mix.slide.loaded
* microsoft.office.mix.stopped

### Testing Events for Content Experiments

* xmodule.partitions.assigned_user_to_partition
* xblock.split_test.child_render

### Student Cohort Events

* edx.cohort.created
* edx.cohort.user_added
* edx.cohort.user_removed


### Teams-Related Events

* edx.team.activity_updated
* edx.team.changed
* edx.team.created
* edx.team.deleted
* edx.team.learner_added
* edx.team.learner_removed
* edx.team.page_viewed
* edx.team.searched

### Certificate Events

* edx.certificate.created
* edx.certificate.shared
* edx.certificate.evidence_visited

### Open Response Assessment Events (Deprecated)

ignored

**Comment by quitterie-lcs** [comment]
#Completion check-list

As base pydantic models have been defined according to the event_source, all events will be implemented according to it. 
The check-list of implementation completion is based on the following classification:

## Server

- [ ] edx.course.enrollment.activated
- [ ] edx.course.enrollment.deactivated
- [ ] edx.course.enrollment.mode_changed
- [ ] edx.course.enrollment.upgrade.succeeded
- [ ] edx.problem.hint.demandhint_displayed
- [ ] edx.problem.hint.feedback_displayed
- [ ] problem_check
- [ ] problem_check_fail
- [ ] problem_graded
- [ ] problem_rescore
- [ ] problem_rescore_fail
- [ ] reset_problem
- [ ] reset_problem_fail
- [ ] save_problem_fail
- [ ] save_problem_success
- [ ] showanswer
- [ ] edx.special_exam.proctored.attempt.created
- [ ] edx.special_exam.practice.attempt.created
- [ ] edx.special_exam.timed.attempt.created
- [ ] edx.special_exam.proctored.attempt.declined
- [ ] edx.special_exam.proctored.attempt.deleted
- [ ] edx.special_exam.practice.attempt.deleted
- [ ] edx.special_exam.timed.attempt.deleted
- [ ] edx.special_exam.proctored.attempt.download_software_clicked 
- [ ] edx.special_exam.practice.attempt.download_software_clicked
- [ ] edx.special_exam.proctored.attempt.error
- [ ] edx.special_exam.practice.attempt.error
- [ ] edx.special_exam.proctored.attempt.ready_to_start
- [ ] edx.special_exam.practice.attempt.ready_to_start
- [ ] edx.special_exam.proctored.attempt.ready_to_submit
- [ ] edx.special_exam.practice.attempt.ready_to_submit
- [ ] edx.special_exam.timed.attempt.ready_to_submit
- [ ] edx.special_exam.proctored.attempt.rejected
- [ ] edx.special_exam.proctored.attempt.review_received
- [ ] edx.special_exam.proctored.attempt.started
- [ ] edx.special_exam.practice.attempt.started
- [ ] edx.special_exam.timed.attempt.started
- [ ] edx.special_exam.proctored.attempt.submitted
- [ ] edx.special_exam.practice.attempt.submitted
- [ ] edx.special_exam.timed.attempt.submitted
- [ ] edx.special_exam.proctored.attempt.verified
- [ ] edx.special_exam.proctored.option-presented
- [ ] edx.librarycontentblock.content.assigned
- [ ] edx.librarycontentblock.content.removed
- [ ] edx.forum.comment.created
- [ ] edx.forum.response.created
- [ ] edx.forum.response.voted
- [ ] edx.forum.searched
- [ ] edx.forum.thread.created
- [ ] edx.forum.thread.voted
- [ ] openassessmentblock.get_peer_submission
- [ ] openassessmentblock.get_submission_for_staff_grading
- [ ] openassessmentblock.peer_assess
- [ ] openassessmentblock.self_assess
- [ ] openassessmentblock.staff_assess
- [ ] openassessmentblock.submit_feedback_on_assessments
- [ ] openassessmentblock.create_submission
- [ ] openassessmentblock.save_submission
- [ ] openassessment.student_training_assess_example
- [ ] edx.drag_and_drop_v2.feedback.closed
- [ ] edx.drag_and_drop_v2.feedback.opened
- [ ] edx.drag_and_drop_v2.item.dropped
- [ ] edx.drag_and_drop_v2.item.picked_up
- [ ] edx.drag_and_drop_v2.loaded
- [ ] ubc.peer_instruction.accessed
- [ ] ubc.peer_instruction.original_submitted
- [ ] ubc.peer_instruction.revised_submitted
- [ ] xblock.poll.submitted
- [ ] xblock.poll.view_results
- [ ] xblock.survey.submitted
- [ ] xblock.survey.view_results
- [ ] edx.done.toggled
- [ ] edx.googlecomponent.calendar.displayed
- [ ] edx.googlecomponent.document.displayed
- [ ] oppia.exploration.completed
- [ ] oppia.exploration.loaded
- [ ] oppia.exploration.state.changed
- [ ] microsoft.office.mix.loaded
- [ ] microsoft.office.mix.paused
- [ ] microsoft.office.mix.played
- [ ] microsoft.office.mix.slide.loaded
- [ ] microsoft.office.mix.stopped
- [ ] xblock.split_test.child_render
- [ ] edx.cohort.created
- [ ] edx.cohort.user_added
- [ ] edx.cohort.user_removed
- [ ] edx.team.activity_updated
- [ ] edx.team.changed
- [ ] edx.team.created
- [ ] edx.team.deleted
- [ ] edx.team.learner_added
- [ ] edx.team.learner_removed
- [ ] edx.team.searched
- [ ] edx.certificate.created

## Browser

- [ ] edx.course.enrollment.upgrade.clicked
- [ ] page_close
- [ ] seq_goto
- [ ] seq_next
- [ ] seq_prev
- [ ] hide_transcript/edx.video.transcript.hidden
- [ ] load_video/edx.video.loaded
- [ ] pause_video/edx.video.paused
- [ ] play_video/edx.video.played
- [ ] seek_video/edx.video.position.changed
- [ ] show_transcript/edx.video.transcript.shown
- [ ] speed_change_video
- [ ] stop_video/edx.video.stopped
- [ ] video_hide_cc_menu
- [ ] video_show_cc_menu
- [ ] edx.video.bumper.dismissed
- [ ] edx.video.bumper.loaded
- [ ] edx.video.bumper.played
- [ ] edx.video.bumper.skipped
- [ ] edx.video.bumper.stopped
- [ ] edx.video.bumper.transcript.hidden
- [ ] edx.video.bumper.transcript.menu.hidden
- [ ] edx.video.bumper.transcript.menu.shown
- [ ] edx.video.bumper.transcript.shown
- [ ] book
- [ ] textbook.pdf.thumbnails.toggled
- [ ] textbook.pdf.thumbnail.navigated
- [ ] textbook.pdf.outline.toggled
- [ ] textbook.pdf.chapter.navigated
- [ ] textbook.pdf.page.navigated
- [ ] textbook.pdf.zoom.buttons.changed
- [ ] textbook.pdf.zoom.menu.changed
- [ ] textbook.pdf.display.scaled
- [ ] textbook.pdf.page.scrolled
- [ ] textbook.pdf.search.executed
- [ ] textbook.pdf.search.navigatednext
- [ ] textbook.pdf.search.highlight.toggled
- [ ] textbook.pdf.searchcasesensitivity.toggled
- [ ] problem_check
- [ ] problem_reset
- [ ] problem_save
- [ ] problem_show
- [ ] edx.bookmark.accessed
- [ ] edx.bookmark.added
- [ ] edx.bookmark.listed
- [ ] edx.bookmark.removed
- [ ] edx.course.student_notes.added
- [ ] edx.course.student_notes.deleted
- [ ] edx.course.student_notes.edited
- [ ] edx.course.student_notes.notes_page_viewed
- [ ] edx.course.student_notes.searched
- [ ] edx.course.student_notes.used_unit_link
- [ ] edx.course.student_notes.viewed
- [ ] openassessment.upload_file
- [ ] edx.done.toggled
- [ ] xmodule.partitions.assigned_user_to_partition
- [ ] edx.team.page_viewed
- [ ] edx.certificate.shared
- [ ] edx.certificate.evidence_visited

## Mobile

- [ ] hide_transcript/edx.video.transcript.hidden
- [ ] load_video/edx.video.loaded
- [ ] pause_video/edx.video.paused
- [ ] play_video/edx.video.played
- [ ] seek_video/edx.video.position.changed
- [ ] show_transcript/edx.video.transcript.shown
- [ ] stop_video/edx.video.stopped

## Task

Nothing

**Comment by quitterie-lcs** [comment]
# Completion check-list (WIP)


## Video events (with `marsha`)

- [ ] VideoCompleted
- [ ] VideoInitialized
- [ ] VideoInteracted
- [ ] VideoPaused
- [ ] VideoPlayed
- [ ] VideoSeeked
- [ ] VideoTerminated

## Live events (with `marsha`)

- ask to go on stage (for user)
- leave stage (for user)
- accept a user on stage (for moderator)
- reject a user to go on stage (for moderator)
- kick out a user from stage (for moderator)
- connect chat
- seize username
- write message

## Forum events (with `ashley`)
- view a topic
- view a forum
- search a forum
- search a topic in a forum
- reply to a topic

**Comment by quitterie-lcs** [comment]
Marsha events (de)serialisers have been implemented for video and documents. Ashley events (de)serialisers will be adressed in the redefinition of forum events (see issue #233)
